// translations/navbar.js
export const navbarTranslations = {
  en: {
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    faq: "FAQ",
    demo: "Get a Demo",
  },
  es: {
    home: "Inicio",
    about: "Acerca de",
    services: "Servicios",
    contact: "Contacto",
    faq: "Preguntas",
    demo: "Solicitar Demo",
  },
  fr: {
    home: "Accueil",
    about: "À propos",
    services: "Services",
    contact: "Contact",
    faq: "FAQ",
    demo: "Demander une démo",
  },
  de: {
    home: "Startseite",
    about: "Über uns",
    services: "Dienstleistungen",
    contact: "Kontakt",
    faq: "FAQ",
    demo: "Demo anfordern",
  },
  it: {
    home: "Home",
    about: "Chi Siamo",
    services: "Servizi",
    contact: "Contatto",
    faq: "FAQ",
    demo: "Richiedi Demo",
  },
  ar: {
    home: "الصفحة الرئيسية",
    about: "معلومات عنا",
    services: "الخدمات",
    contact: "اتصال",
    faq: "الأسئلة الشائعة",
    demo: "احصل على عرض تجريبي",
  },
  ja: {
    home: "ホーム",
    about: "約",
    services: "サービス",
    contact: "連絡先",
    faq: "よくある質問",
    demo: "デモを依頼",
  },
  ko: {
    home: "홈",
    about: "회사소개",
    services: "서비스",
    contact: "연락처",
    faq: "자주 묻는 질문",
    demo: "데모 요청",
  },
  "zh-CN": {
    home: "首页",
    about: "关于我们",
    services: "服务",
    contact: "联系",
    faq: "常见问题",
    demo: "获取演示",
  },
};